//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.DBModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ACCOUNT
    {
        [Key]
        public short accountID { get; set; }

        public string userName { get; set; }
        public string pass { get; set; }
        public virtual ICollection<USER> USERS { get; set; }

        public ACCOUNT()
        {
            this.USERS = new HashSet<USER>();
        }           
    }
}
