//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.DBModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class APPRECIATION
    {
        [Key]
        public short appreciaID { get; set; }

        public Nullable<short> userID { get; set; }
        public Nullable<short> locationID { get; set; }
        public Nullable<short> numStar { get; set; }
        public string appreciaSubject { get; set; }
        public string content { get; set; }
    
        public virtual LOCATION LOCATION { get; set; }
        public virtual USER USER { get; set; }
    }
}
