//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.DBModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class APPRECIATION
    {
        [Key]
        public short appreciaID { get; set; }

        public string userFBID { get; set; }
        public string userFBName { get; set; }
        public short locationID { get; set; }
        public short numStar { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public DateTime date { get; set; }

        public string numStarString
        {
            get
            {
                string nss = "";
                for (int i = 0; i < numStar + 1; i++)
                    nss += "✪";

                return nss;
            }
        }

        public virtual LOCATION LOCATION { get; set; }
    }
}
