//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICON
    {        
        public ICON()
        {
            this.LOCATION_TYPE = new HashSet<LOCATION_TYPE>();
        }

        [System.ComponentModel.DataAnnotations.Key]
        public short iconID { get; set; }
        public string iconSource { get; set; }
           
        public virtual ICollection<LOCATION_TYPE> LOCATION_TYPE { get; set; }
    }
}
