//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGE
    {
        [System.ComponentModel.DataAnnotations.Key]
        public short imageID { get; set; }
        public string imageSource { get; set; }
        public Nullable<short> articleID { get; set; }
    
        public virtual ARTICLE ARTICLE { get; set; }
    }
}
