//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {        
        public LOCATION()
        {
            this.APPRECIATIONs = new HashSet<APPRECIATION>();
            this.ARTICLEs = new HashSet<ARTICLE>();
            this.SCHEDULE_TEMPLATE = new HashSet<SCHEDULE_TEMPLATE>();
            this.TRANSPORTATIONs = new HashSet<TRANSPORTATION>();
            this.VIDEOs = new HashSet<VIDEO>();
        }

        [System.ComponentModel.DataAnnotations.Key]
        public short locationID { get; set; }
        public string locationName { get; set; }
        public string locationAddress { get; set; }
        public string phoneNumber { get; set; }
        public string mapImageSource { get; set; }
        public Nullable<decimal> priceMin { get; set; }
        public Nullable<decimal> priceMax { get; set; }
        public string website { get; set; }
        public Nullable<float> longitude { get; set; }
        public Nullable<float> latitude { get; set; }
        public Nullable<short> typeID { get; set; }
        public Nullable<short> provinceID { get; set; }
    
        public virtual ICollection<APPRECIATION> APPRECIATIONs { get; set; }
        public virtual ICollection<ARTICLE> ARTICLEs { get; set; }
        public virtual LOCATION_TYPE LOCATION_TYPE { get; set; }
        public virtual PROVINCE PROVINCE { get; set; }
        public virtual ICollection<SCHEDULE_TEMPLATE> SCHEDULE_TEMPLATE { get; set; }
        public virtual ICollection<TRANSPORTATION> TRANSPORTATIONs { get; set; }
        public virtual ICollection<VIDEO> VIDEOs { get; set; }
    }
}
