//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION_TYPE
    {
        public LOCATION_TYPE()
        {
            this.LOCATIONS = new HashSet<LOCATION>();
        }

        [System.ComponentModel.DataAnnotations.Key]
        public short typeID { get; set; }
        public string typeName { get; set; }
        public Nullable<short> iconID { get; set; }
    
        public virtual ICON ICON { get; set; }
        public virtual ICollection<LOCATION> LOCATIONS { get; set; }
    }
}
