//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_TRIP
    {
        [System.ComponentModel.DataAnnotations.Key]
        public short planID { get; set; }
        public string planName { get; set; }
        public string detail { get; set; }
        public Nullable<short> userID { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
