//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.DBModels
{
    using System;
    using System.Collections.Generic;

    public partial class PROVINCE
    {
        public PROVINCE()
        {
            this.CITies = new HashSet<CITY>();
            this.LOCATIONS = new HashSet<LOCATION>();
        }

        [System.ComponentModel.DataAnnotations.Key]
        public short provinceID { get; set; }
        public string provinceName { get; set; }
        public string imageSource { get; set; }
        public string suggestSentence { get; set; }
        public string intro { get; set; }
        public Nullable<float> longtitude { get; set; }
        public Nullable<float> latitude { get; set; }
        public Nullable<float> totalArea { get; set; }
        public Nullable<float> populationProvince { get; set; }
        public Nullable<short> regionID { get; set; }
    
        public virtual ICollection<CITY> CITies { get; set; }
        public virtual ICollection<LOCATION> LOCATIONS { get; set; }
        public virtual REGION REGION { get; set; }
    }
}
