//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGION
    {
        public REGION()
        {
            this.PROVINCEs = new HashSet<PROVINCE>();
        }

        [System.ComponentModel.DataAnnotations.Key]
        public short regionID { get; set; }
        public string regionName { get; set; }
    
        public virtual ICollection<PROVINCE> PROVINCEs { get; set; }
    }
}
