//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_TEMPLATE
    {
        [System.ComponentModel.DataAnnotations.Key]
        public short scheduleID { get; set; }
        public string scheduleDetail { get; set; }
        public Nullable<decimal> expectedCharge { get; set; }
        public Nullable<short> locationID { get; set; }
    
        public virtual LOCATION LOCATION { get; set; }
    }
}
