//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEO
    {
        [System.ComponentModel.DataAnnotations.Key]
        public short videoID { get; set; }
        public string videoName { get; set; }
        public string videoSource { get; set; }
        public Nullable<short> locationID { get; set; }
    
        public virtual LOCATION LOCATION { get; set; }
    }
}
